### ISSUE TITLE
[route][table][db]New routes to record time related metrics from devices

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-api#114]
## 🚀 Feature

[] Add table to record metrics (cpu and memory usage, temperature) from pi devices

[] Create related routes

[] Update client consequently

## Motivation

In order to design a suitable system, some metrics should be recorded.
After test phases, the output can be analyzed to understand how to improve the system or understand why it crashed.
As an example, in order to know if fans, heatsink are needed, cpu temperature can be recorded; Or, some performance about cpu usage or memory available could help to select the best raspberry pi model fitting our needs.

Moreover, it will help us to monitor systems.

## Pitch

Hence, a new table needs to be created, and could look like this :

device_id | datetime | measure_name | value | units
-- |-- | -- | -- | --

It will be time related metrics having only relation with devices. 

Hence, for sake of simplicity, it can be stored in our postgre table (Otherwise it would implies a specific db system, what do you think)

Granularity of metrics might be around every 10min

This is completely open to discussion about and all suggestion are welcomed

**Comment by frgfm** [comment]
Considering the temporality of those entries, this represents a significant table, which sounds more to me like logs. Perhaps we should consider investigating monitoring solutions first (catching the logs and providing a dashboard).

Otherwise, this will easily become our biggest table and source of traffic through the API :sweat_smile:

**Comment by fe51** [comment]
Yes, I agree with you this is more like logs, and would be pertinent to go for a suitable log solution. retaining those information eternally is not useful, and we should estimate how long this information will be stored.


And if there is a way to avoid a massive table, let's go for it !

@2ndcouteau @chloeskt @blenzi what do you think ?

**Comment by chloeskt** [comment]
Hi ! Last time, @2ndcouteau mentionned the potential use of [ELK](https://www.elastic.co/fr/what-is/elk-stack), I think it could be a nice solution and it's kinda made for such scenarios.

Regarding the time, I guess we could store this info for a week or less ?

**Comment by frgfm** [comment]
Since we are going for the log export option, I think it would be better to either move forward with the topic on https://github.com/pyronear/pyro-sys-setup or https://github.com/pyronear/pyro-engine (since it won't go through the API). If so, let's close the issue and open a follow-up one in the corresponding repo :)

**Comment by frgfm** [comment]
As per my previous comment, I'm closing this issue. Feel free to reopen if you think I missed something :ok_hand:
