### ISSUE TITLE
Discussion: Client-side API

### ISSUE THREAD

**Issue by florianriche** [pyronear/pyro-api#24]
We need to develop on Client-side (Device) in order to send information to the API.

The devices will need to: 
* Ping the API
* Send alerts
* Send medias
* Send positions (if using GPS )
Those messages will rely on a token that should be stored on the client-side.

Now comes the question: how to develop that client-side capability?
- Do we alter the CV component to have a main that sends messages to the API when it detect something. This could end up being a bit of spaghetti code and make the purpose of the package less clear
- Do we create a totally new component whose goal is to deploy on a device. This client would communicate with the API and call the CV component to look for fires. This would increase the number of repos.

**Comment by frgfm** [comment]
Hey @florianriche,

Thanks for opening the issue!
More specifically in terms of routes, here is what I think about for client-side:
- `devices/heartbeat`: updating last known ping
- `devices/location`: updating last known position
_Side note: I just noticed we do have a method to update the location of a device, but not to update the current device (since they might have GPS modules). I just opened an issue for this #32_ 
- `media/post`: creating a new media entry
- `media/upload`: uploading the content media to a remote bucket / storage + updating the `key`/`path` of the corresponding media in the table
- `alerts/post`: creating a new alert (we might also have to think about whether it should be creating the involved event)

About the implementation, I'm not very knowledgeable about best practices here. But perhaps we could try to develop a python library on this repo, simply in a different folder ("client"). This would ease the testing & documentation processes?

**Comment by florianriche** [comment]
I think what you suggest (to use a client folder) is the goto solution.
I think we could also use this occasion to write a deployment script that could deploy the solution on a Rasperry.
1: Retrieve the Device Auth Token (after asking the login/pwd during a prompt)
2: Store that Token in a .env file
3: Launch the Pyronear client.

I can do it unless someone wants to take care of it ?

**Comment by frgfm** [comment]
go for it @florianriche ;)
There are so many open issues right now, that it would be good to get on closing some haha
